try{
    alert("Start of try runs");
    //...no errors here
    alert("End of try runs");
}
catch(err){
    
}