<h1>Error Handling / TRY CATCH</h1>


<h2>Pada pertemuan ke 03-01 ini mempelajari mengenai Error Handling</h2>
<h3>Try Catch Syntax</h3>
<p>Try dijalankan pertama kali, ketika tidak ada error terjadi maka blok catch diabaikan.
Ketika try menemukan error maka catch akan mengeksekusi blok catch.</p>
<h3>try catch only works for runtime errors</h3>
<p>Try Catch hanya bisa mengendalikan error yg terjadi jk codenya valid (kode yg masih bs dimengerti oleh mesin). Itu disebut sbg runtime error / exceptions</p>
<h3>try catch works synchronously</h3>
<p>Ketika error / exceptions terjadi secara terjadwal seperti "setTimeout" maka try catch tdk akan menanganinya, karena fungsi akan dijalankan nanti ketika mesin sudah meninggalkan construct try catch.
untuk menangkap error di dalam fungsi schedule, try catch harus berada di dalam sebuah fungsi.</p>
<h3>Finally</h3>
<p>"Finally" clause sering digunakan ketika kita melakukan sesuatu dan ingin mengakhirinya dalam hasil apapun.</p>